name: Build Image using Containerfile and Push Image to Quay.io on Push and schedule
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 14 * * 1'
jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: jenkins-python3.6.8-pip
      IMAGE_TAGS: latest

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        base-image: jenkins/jenkins:lts-centos7
        dockerfiles: |
          ./Dockerfile

    - name: Push To Quay
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ secrets.QUAY_REPO }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Use the image
      run: echo "New image has been pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
    
